spring:
  mvc:
    async:
      request-timeout: -1

server:
  port: ${SERVER_PORT:8080}

service:
  image: ${SERVICE_IMAGE:assalielmehdi/judge}
  cmd: ${SERVICE_CMD:judge}
  test_cmd: ${SERVICE_TEST_CMD:test}

config:
  max_running_containers: 10